### ISSUE TITLE
List all created custom commands

### ISSUE THREAD

**Issue by nehaAgarwal96** [hiralbhanu/GITS2.1-I.R.I.S#1]
Create a command that allows the user to see ALL of the CUSTOM commands they have created till now.

**Comment by hiralbhanu** [comment]
I am not able to integrate the py file with the command name

**Comment by hrushabhchouhan** [comment]
What exactly is the issue? If you have solved it already, how did you do it?

**Comment by hiralbhanu** [comment]
Had to integrate the command in gits.py file in code
