### ISSUE TITLE
Implement new feature to count the total number of commits of a given repository

### ISSUE THREAD

**Issue by hrushabhchouhan** [hiralbhanu/GITS2.1-I.R.I.S#10]
Work in progress

**Comment by hrushabhchouhan** [comment]
Hey guys, I'm facing this issue since morning : How are we supposed to index a Namespace() object?
Is there any other way to take the arguments for the count_commits function?

**Comment by nehaAgarwal96** [comment]
I got the issue. I think that, instead of passing the get_repo_name function directly as an argument, it would be better if you call the function inside the definition of count_commits function. I think that the issue might get resolved in this way.

**Comment by hrushabhchouhan** [comment]
Ohh okay, I got it, will start working on it. Thank you!

**Comment by apoorvacha** [comment]
Were you able to fix the issue ?

**Comment by hrushabhchouhan** [comment]
Yes, I have uploaded the code file

**Comment by hiralbhanu** [comment]
Awesome work!

**Comment by hrushabhchouhan** [comment]
Thanks!
