### ISSUE TITLE
Showing the Good Repository Score or Grade after gits push

### ISSUE THREAD

**Issue by nehaAgarwal96** [hiralbhanu/GITS2.1-I.R.I.S#2]
Integrate the https://github.com/MeghanaVasist/constable-github-action project to show the final good repository score report in the command line after the gits push command is executed.

**Comment by nehaAgarwal96** [comment]
Hey guys, I just confirmed with the previous team that we are supposed to just use the logic of constable and that we can implement the same in python.

**Comment by hrushabhchouhan** [comment]
Ohh okay, now it makes alot of sense, since we are supposed to show the good repo grade on the terminal and not using a web app.

**Comment by nehaAgarwal96** [comment]
This functionality has been implemented successfully.
