### ISSUE TITLE
Documentation for gits creategoodrepo command

### ISSUE THREAD

**Issue by hiralbhanu** [hiralbhanu/GITS2.1-I.R.I.S#3]

**Comment by apoorvacha** [comment]
GitHub CLI uses sak007/goodRepo_template to create a good repository. This template will be used by git only if present on local, to create a directory on local but will not initialize a repo on GitHub. To create a good repo using git commands, first it will be created on local and then we need to make a repo on GitHub and push the directory from local to the GitHub. Hence this issue can not be automated completely.
