### ISSUE TITLE
Add version command

### ISSUE THREAD

**Issue by hiralbhanu** [hiralbhanu/GITS2.1-I.R.I.S#4]
Add a gits version command to see the current version of git and gits

**Comment by hiralbhanu** [comment]
Working on the documentation of the version.py file

**Comment by nehaAgarwal96** [comment]
Do you need any help in the implementation of this?

**Comment by hiralbhanu** [comment]
No. The implementation is done

**Comment by apoorvacha** [comment]
Well done guys
