### ISSUE TITLE
Refactor creategoodrepo to use only git commands and not gh (GitHub CLI)

### ISSUE THREAD

**Issue by hrushabhchouhan** [hiralbhanu/GITS2.1-I.R.I.S#6]
We need to refactor the "creategoodrepo" to use only git commands internally.

**Comment by apoorvacha** [comment]
If git command is not used then the creation of new repository will also depend on gh,  which is not necessarily installed on all machines

**Comment by nehaAgarwal96** [comment]
Okay, how do we go about this then?

**Comment by apoorvacha** [comment]
GitHub CLI uses sak007/goodRepo_template to create a good repository. This template will be used by git only if present on local, to create a directory on local but will not initialize a repo on GitHub.  To create a good repo using git commands, first it will be created on local and then we need to make a repo on GitHub and push the directory from local to the GitHub. Hence this issue can not be automated completely.
