### ISSUE TITLE
Failing test case in test_gits_push.py

### ISSUE THREAD

**Issue by hrushabhchouhan** [hiralbhanu/GITS2.1-I.R.I.S#7]
Hey guys, I tried testing the gits_push.py file and I found that one test case is failing.

**Comment by nehaAgarwal96** [comment]
The error is in which function?

**Comment by hrushabhchouhan** [comment]
The 'get_repo_name' function in helper.py

**Comment by nehaAgarwal96** [comment]
I have fixed the get_repo_name() function, try running the test cases now.

**Comment by hrushabhchouhan** [comment]
That's awesome! All test cases are running now.
